### ISSUE TITLE
'Options' object has no attribute 'child_relations'

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtailapi#2]
When accessing /api/v1/pages/ I encountered the following error:

```
AttributeError at /api/v1/pages/
'Options' object has no attribute 'child_relations'
```

Trying different values for the "type" query parameter has some Page types resulting in the above error and others that don't. The line at the source link below seems to be the cause:

https://github.com/torchbox/wagtailapi/blob/master/wagtailapi/api.py#L34

Wagtail: 0.8.4
Django: 1.7.1
WagtailApi: 1.0b2

**Comment by gasman** [comment]
It looks like this code ought to be using `modelcluster.models.get_all_child_relations` instead: https://github.com/torchbox/django-modelcluster#introspection

**Comment by kaedroho** [comment]
Just pushed a new release with the fix @gasman suggested. Could you update to the latest version (`1.0b3`) and let me know if it fixes your issue?

**Comment by mhnbcu** [comment]
No longer seeing this issue in 1.0b3
