### ISSUE TITLE
/pages/ endpoint displays 1 page of 2 or more with same title and parent

### ISSUE THREAD

**Issue by mhnbcu** [torchbox/wagtailapi#3]
When there are 2 or more pages with the same title and parent only 1 of them will be displayed in the listing along with other pages having different titles. 

This was encountered when testing multiple pages having the same title but different slugs. 

Wagtail: 0.8.4
Django: 1.7.1
Wagtail API: 1.0b3

**Comment by kaedroho** [comment]
Hi @mhnbcu 
I'm having difficulty reproducing this issue. I've added a new page called "Blog post" to the demo site, and it appears alongsite another page with the same name and parent: http://wagtailapi.kaed.uk/api/v1/pages/?child_of=5
And also on the main listing: http://wagtailapi.kaed.uk/api/v1/pages/

Please feel free to try to reproduce this on the test site. The admin login details are: `admin/changeme`

**Comment by mhnbcu** [comment]
@kaedroho After adding a Blog post to the demo site the 2 pages with the same title display at http://wagtailapi.kaed.uk/api/v1/pages/?child_of=2 but not at http://wagtailapi.kaed.uk/api/v1/pages/. Is this due to pagination?

**Comment by kaedroho** [comment]
Yep, it looks like pagination is kicking in now. You can see page 2 here: http://wagtailapi.kaed.uk/api/v1/pages/?offset=20

**Comment by mhnbcu** [comment]
@kaedroho Thanks. Using offset on my local install displays the 2nd item as well. My mistake!
